#ifndef _KEYCODES_H_
#define _KEYCODES_H_

#define KEYCODE_NONE                              0x00
#define KEYCODE_ERROR_ROLLOVER                    0x01
#define KEYCODE_POST_FAIL                         0x02
#define KEYCODE_ERROR_UNDEFINED                   0x03
#define KEYCODE_A                                 0x04
#define KEYCODE_B                                 0x05
#define KEYCODE_C                                 0x06
#define KEYCODE_D                                 0x07
#define KEYCODE_E                                 0x08
#define KEYCODE_F                                 0x09
#define KEYCODE_G                                 0x0A
#define KEYCODE_H                                 0x0B
#define KEYCODE_I                                 0x0C
#define KEYCODE_J                                 0x0D
#define KEYCODE_K                                 0x0E
#define KEYCODE_L                                 0x0F
#define KEYCODE_M                                 0x10
#define KEYCODE_N                                 0x11
#define KEYCODE_O                                 0x12
#define KEYCODE_P                                 0x13
#define KEYCODE_Q                                 0x14
#define KEYCODE_R                                 0x15
#define KEYCODE_S                                 0x16
#define KEYCODE_T                                 0x17
#define KEYCODE_U                                 0x18
#define KEYCODE_V                                 0x19
#define KEYCODE_W                                 0x1A
#define KEYCODE_X                                 0x1B
#define KEYCODE_Y                                 0x1C
#define KEYCODE_Z                                 0x1D
#define KEYCODE_1_AND_EXCLAMATION                 0x1E
#define KEYCODE_2_AND_AT                          0x1F
#define KEYCODE_3_AND_HASHMARK                    0x20
#define KEYCODE_4_AND_DOLLAR                      0x21
#define KEYCODE_5_AND_PERCENTAGE                  0x22
#define KEYCODE_6_AND_CARET                       0x23
#define KEYCODE_7_AND_AND_AMPERSAND               0x24
#define KEYCODE_8_AND_ASTERISK                    0x25
#define KEYCODE_9_AND_OPENING_PARENTHESIS         0x26
#define KEYCODE_0_AND_CLOSING_PARENTHESIS         0x27
#define KEYCODE_ENTER                             0x28
#define KEYCODE_ESCAPE                            0x29
#define KEYCODE_BACKSPACE                         0x2A
#define KEYCODE_TAB                               0x2B
#define KEYCODE_SPACE                             0x2C
#define KEYCODE_MINUS_AND_UNDERSCORE              0x2D
#define KEYCODE_EQUAL_AND_PLUS                    0x2E
#define KEYCODE_OPENING_BRACKET_AND_OPENING_BRACE 0x2F
#define KEYCODE_CLOSING_BRACKET_AND_CLOSING_BRACE 0x30
#define KEYCODE_BACKSLASH_AND_PIPE                0x31
#define KEYCODE_NON_US_HASHMARK_AND_TILDE         0x32
#define KEYCODE_SEMICOLON_AND_COLON               0x33
#define KEYCODE_APOSTROPHE_AND_QUOTE              0x34
#define KEYCODE_GRAVE_ACCENT_AND_TILDE            0x35
#define KEYCODE_COMMA_AND_LESS_THAN_SIGN          0x36
#define KEYCODE_DOT_AND_GREATER_THAN_SIGN         0x37
#define KEYCODE_SLASH_AND_QUESTION_MARK           0x38
#define KEYCODE_CAPS_LOCK                         0x39
#define KEYCODE_F1                                0x3A
#define KEYCODE_F2                                0x3B
#define KEYCODE_F3                                0x3C
#define KEYCODE_F4                                0x3D
#define KEYCODE_F5                                0x3E
#define KEYCODE_F6                                0x3F
#define KEYCODE_F7                                0x40
#define KEYCODE_F8                                0x41
#define KEYCODE_F9                                0x42
#define KEYCODE_F10                               0x43
#define KEYCODE_F11                               0x44
#define KEYCODE_F12                               0x45
#define KEYCODE_PRINT_SCREEN                      0x46
#define KEYCODE_SCROLL_LOCK                       0x47
#define KEYCODE_PAUSE                             0x48
#define KEYCODE_INSERT                            0x49
#define KEYCODE_HOME                              0x4A
#define KEYCODE_PAGE_UP                           0x4B
#define KEYCODE_DELETE                            0x4C
#define KEYCODE_END                               0x4D
#define KEYCODE_PAGE_DOWN                         0x4E
#define KEYCODE_RIGHT_ARROW                       0x4F
#define KEYCODE_LEFT_ARROW                        0x50
#define KEYCODE_DOWN_ARROW                        0x51
#define KEYCODE_UP_ARROW                          0x52
#define KEYCODE_NUM_LOCK                          0x53
#define KEYCODE_KEYPAD_SLASH                      0x54
#define KEYCODE_KEYPAD_ASTERISK                   0x55
#define KEYCODE_KEYPAD_MINUS                      0x56
#define KEYCODE_KEYPAD_PLUS                       0x57
#define KEYCODE_KEYPAD_ENTER                      0x58
#define KEYCODE_KEYPAD_1_AND_END                  0x59
#define KEYCODE_KEYPAD_2_AND_DOWN_ARROW           0x5A
#define KEYCODE_KEYPAD_3_AND_PAGE_DOWN            0x5B
#define KEYCODE_KEYPAD_4_AND_LEFT_ARROW           0x5C
#define KEYCODE_KEYPAD_5                          0x5D
#define KEYCODE_KEYPAD_6_AND_RIGHT_ARROW          0x5E
#define KEYCODE_KEYPAD_7_AND_HOME                 0x5F
#define KEYCODE_KEYPAD_8_AND_UP_ARROW             0x60
#define KEYCODE_KEYPAD_9_AND_PAGE_UP              0x61
#define KEYCODE_KEYPAD_0_AND_INSERT               0x62
#define KEYCODE_KEYPAD_DOT_AND_DELETE             0x63
#define KEYCODE_NON_US_BACKSLASH_AND_PIPE         0x64
#define KEYCODE_APPLICATION                       0x65
#define KEYCODE_POWER                             0x66
#define KEYCODE_KEYPAD_EQUAL_SIGN                 0x67
#define KEYCODE_F13                               0x68
#define KEYCODE_F14                               0x69
#define KEYCODE_F15                               0x6A
#define KEYCODE_F16                               0x6B
#define KEYCODE_F17                               0x6C
#define KEYCODE_F18                               0x6D
#define KEYCODE_F19                               0x6E
#define KEYCODE_F20                               0x6F
#define KEYCODE_F21                               0x70
#define KEYCODE_F22                               0x71
#define KEYCODE_F23                               0x72
#define KEYCODE_F24                               0x73
#define KEYCODE_EXECUTE                           0x74
#define KEYCODE_HELP                              0x75
#define KEYCODE_MANU                              0x76
#define KEYCODE_SELECT                            0x77
#define KEYCODE_STOP                              0x78
#define KEYCODE_AGAIN                             0x79
#define KEYCODE_UNDO                              0x7A
#define KEYCODE_CUT                               0x7B
#define KEYCODE_COPY                              0x7C
#define KEYCODE_PASTE                             0x7D
#define KEYCODE_FIND                              0x7E
#define KEYCODE_MUTE                              0x7F
#define KEYCODE_VOLUME_UP                         0x80
#define KEYCODE_VOLUME_DOWN                       0x81
#define KEYCODE_LOCKING_CAPS_LOCK                 0x82
#define KEYCODE_LOCKING_NUM_LOCK                  0x83
#define KEYCODE_LOCKING_SCROLL_LOCK               0x84
#define KEYCODE_KEYPAD_COMMA                      0x85
#define KEYCODE_KEYPAD_EQUAL_SIGN_AS400           0x86
#define KEYCODE_INTERNATIONAL1                    0x87
#define KEYCODE_INTERNATIONAL2                    0x88
#define KEYCODE_INTERNATIONAL3                    0x89
#define KEYCODE_INTERNATIONAL4                    0x8A
#define KEYCODE_INTERNATIONAL5                    0x8B
#define KEYCODE_INTERNATIONAL6                    0x8C
#define KEYCODE_INTERNATIONAL7                    0x8D
#define KEYCODE_INTERNATIONAL8                    0x8E
#define KEYCODE_INTERNATIONAL9                    0x8F
#define KEYCODE_LANG1                             0x90
#define KEYCODE_LANG2                             0x91
#define KEYCODE_LANG3                             0x92
#define KEYCODE_LANG4                             0x93
#define KEYCODE_LANG5                             0x94
#define KEYCODE_LANG6                             0x95
#define KEYCODE_LANG7                             0x96
#define KEYCODE_LANG8                             0x97
#define KEYCODE_LANG9                             0x98
#define KEYCODE_ALTERNATE_ERASE                   0x99
#define KEYCODE_SISREQ                            0x9A
#define KEYCODE_CANCEL                            0x9B
#define KEYCODE_CLEAR                             0x9C
#define KEYCODE_PRIOR                             0x9D
#define KEYCODE_RETURN                            0x9E
#define KEYCODE_SEPARATOR                         0x9F
#define KEYCODE_OUT                               0xA0
#define KEYCODE_OPER                              0xA1
#define KEYCODE_CLEAR_AND_AGAIN                   0xA2
#define KEYCODE_CRSEL_ANDPROPS                    0xA3
#define KEYCODE_EXSEL                             0xA4
#define KEYCODE_KEYPAD_00                         0xB0
#define KEYCODE_KEYPAD_000                        0xB1
#define KEYCODE_THOUSANDS_SEPARATOR               0xB2
#define KEYCODE_DECIMAL_SEPARATOR                 0xB3
#define KEYCODE_CURRENCY_UNIT                     0xB4
#define KEYCODE_CURRENCY_SUB_UNIT                 0xB5
#define KEYCODE_KEYPAD_OPENING_PARENTHESIS        0xB6
#define KEYCODE_KEYPAD_CLOSING_PARENTHESIS        0xB7
#define KEYCODE_KEYPAD_OPENING_BRACE              0xB8
#define KEYCODE_KEYPAD_CLOSING_BRACE              0xB9
#define KEYCODE_KEYPAD_TAB                        0xBA
#define KEYCODE_KEYPAD_BACKSPACE                  0xBB
#define KEYCODE_KEYPAD_A                          0xBC
#define KEYCODE_KEYPAD_B                          0xBD
#define KEYCODE_KEYPAD_C                          0xBE
#define KEYCODE_KEYPAD_D                          0xBF
#define KEYCODE_KEYPAD_E                          0xC0
#define KEYCODE_KEYPAD_F                          0xC1
#define KEYCODE_KEYPAD_XOR                        0xC2
#define KEYCODE_KEYPAD_CARET                      0xC3
#define KEYCODE_KEYPAD_PERCENTAGE                 0xC4
#define KEYCODE_KEYPAD_LESS_THAN_SIGN             0xC5
#define KEYCODE_KEYPAD_GREATER_THAN_SIGN          0xC6
#define KEYCODE_KEYPAD_AMP                        0xC7
#define KEYCODE_KEYPAD_AMP_AMP                    0xC8
#define KEYCODE_KEYPAD_PIPE                       0xC9
#define KEYCODE_KEYPAD_PIPE_PIPE                  0xCA
#define KEYCODE_KEYPAD_COLON                      0xCB
#define KEYCODE_KEYPAD_HASHMARK                   0xCC
#define KEYCODE_KEYPAD_SPACE                      0xCD
#define KEYCODE_KEYPAD_AT                         0xCE
#define KEYCODE_KEYPAD_EXCLAMATION_SIGN           0xCF
#define KEYCODE_KEYPAD_MEMORY_STORE               0xD0
#define KEYCODE_KEYPAD_MEMORY_RECALL              0xD1
#define KEYCODE_KEYPAD_MEMORY_CLEAR               0xD2
#define KEYCODE_KEYPAD_MEMORY_ADD                 0xD3
#define KEYCODE_KEYPAD_MEMORY_SUBTRACT            0xD4
#define KEYCODE_KEYPAD_MEMORY_MULTIPLY            0xD5
#define KEYCODE_KEYPAD_MEMORY_DIVIDE              0xD6
#define KEYCODE_KEYPAD_PLUS_AND_MINUS             0xD7
#define KEYCODE_KEYPAD_CLEAR                      0xD8
#define KEYCODE_KEYPAD_CLEAR_ENTRY                0xD9
#define KEYCODE_KEYPAD_BINARY                     0xDA
#define KEYCODE_KEYPAD_OCTAL                      0xDB
#define KEYCODE_KEYPAD_DECIMAL                    0xDC
#define KEYCODE_KEYPAD_HEXADECIMAL                0xDD
#define KEYCODE_LEFT_CONTROL                      0xE0
#define KEYCODE_LEFT_SHIFT                        0xE1
#define KEYCODE_LEFT_ALT                          0xE2
#define KEYCODE_LEFT_GUI                          0xE3
#define KEYCODE_RIGHT_CONTROL                     0xE4
#define KEYCODE_RIGHT_SHIFT                       0xE5
#define KEYCODE_RIGHT_ALT                         0xE6
#define KEYCODE_RIGHT_GUI                         0xE7

#define KEYCODE_Fn_KEY                            0xFF

#define KEYCODE_KEY_SWITCH_0                      0xF0
#define KEYCODE_KEY_SWITCH_1                      0xF1
#define KEYCODE_KEY_SWITCH_2                      0xF2
#define KEYCODE_KEY_SWITCH_3                      0xF3
#define KEYCODE_KEY_SWITCH_4                      0xF4
#define KEYCODE_KEY_SWITCH_5                      0xF5
#define KEYCODE_KEY_SWITCH_6                      0xF6
#define KEYCODE_KEY_SWITCH_7                      0xF7
#define KEYCODE_KEY_SWITCH_8                      0xF8
#define KEYCODE_KEY_SWITCH_9                      0xF9

#endif
